general:
	chmod 750 /home/tsec/Quantas/tpot/sandbox_analysis
	chmod 750 /home/tsec/Quantas/tpot/sandbox_report

dionaea:
	mkdir -p /data/dionaea/extract_binaries
	touch /data/dionaea/dionaea_analysis.txt
	touch /data/dionaea/dionaea_already_analyzed.txt
	touch /home/tsec/Quantas/tpot/reports/dionaea_report.csv

cowrie:
	mkdir -p /data/cowrie/extract_downloads
	touch /data/cowrie/cowrie_analysis.txt
	touch /data/cowrie/cowrie_already_analyzed.txt
	touch /home/tsec/Quantas/tpot/reports/cowrie_report.csv
	touch /home/tsec/Quantas/tpot/reports/cowrie_not_logged_shasum.txt
	touch /home/tsec/Quantas/tpot/reports/cowrie_ok.txt
	touch /home/tsec/Quantas/tpot/reports/cowrie_not_ok.txt
