general:
	chmod 750 /home/tsec/Quantas/tpot/sandbox_analysis
	chmod 750 /home/tsec/Quantas/tpot/sandbox_report

dionaea:
	mkdir -p /data/dionaea/extract_binaries
	touch /data/dionaea/dionaea_analysis.txt
	touch /data/dionaea/dionaea_already_analyzed.txt

cowrie:
	mkdir -p /data/cowrie/extract_downloads
	touch /data/cowrie/cowrie_analysis.txt
	touch /data/cowrie/cowrie_already_analyzed.txt
